services:
  - type: web
    name: laravel12-react
    plan: starter
    runtime: docker
    dockerfilePath: ./Dockerfile
    preDeployCommand: php artisan migrate --force
    envVars:
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: ep-falling-poetry-adrwnnv5-pooler.c-2.us-east-1.aws.neon.tech
      - key: DB_PORT
        value: 5432
      - key: DB_DATABASE
        value: restaurantdb
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        sync: false
      - key: APP_URL
        sync: false
